
[supervisord]
nodaemon=true
user=root


[program:api]
command=uvicorn main:app --host 0.0.0.0 --reload
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/api.log
stderr_logfile=/app/api.err.log


[program:sitemap]
command=bash -c "while true; do bash update_sitemaps.sh; sleep 10800; done"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/sitemap.log
stderr_logfile=/app/sitemap.err.log
