# Synonyms dictionary for manhwa search
SYNONYMS = {
    "sci-fi": ["science fiction", "scifi", "sci fi", "sci_fi", "sf", "sci-fi", "sci fi", "sci_fi", "science-fiction"],
    "isekai": ["other world", "異世界", "parallel world", "another world", "different world", "isekai", "異世界転生", "異世界転移"],
    "romance": ["love story", "romantic", "rom-com", "romcom", "romance", "恋愛", "romantic comedy"],
    "action": ["fight", "battle", "combat", "action", "アクション", "fighting", "war", "martial arts"],
    "adventure": ["journey", "quest", "exploration", "adventure", "冒険", "travel", "expedition"],
    "fantasy": ["magic", "magical", "fantasy", "ファンタジー", "supernatural", "myth", "mythical", "fairy tale"],
    "drama": ["dramatic", "drama", "ドラマ", "emotional", "tragedy", "slice of life"],
    "comedy": ["funny", "humor", "comedy", "コメディ", "gag", "parody", "satire"],
    "horror": ["scary", "terror", "horror", "ホラー", "thriller", "creepy", "ghost", "monster"],
    "mystery": ["detective", "mystery", "ミステリー", "crime", "suspense", "whodunit", "investigation"],
    "school": ["school life", "academy", "high school", "school", "学園", "student", "campus"],
    "sports": ["athletics", "sports", "スポーツ", "competition", "game", "tournament", "match"],
    "historical": ["history", "historical", "歴史", "period", "ancient", "medieval", "samurai"],
    "shounen": ["少年", "shonen", "young boy", "boy", "少年漫画", "少年向け"],
    "shoujo": ["少女", "shoujo", "young girl", "girl", "少女漫画", "少女向け"],
    "slice of life": ["daily life", "slice of life", "スライスオブライフ", "ordinary life", "real life"],
    "supernatural": ["supernatural", "超自然", "paranormal", "magic", "occult", "spirit", "ghost"],
    "psychological": ["mind", "psychological", "心理", "mental", "psycho", "psychology", "brain"],
    "ecchi": ["ecchi", "エッチ", "fanservice", "sexy", "suggestive", "lewd"],
    "mecha": ["robot", "mecha", "メカ", "giant robot", "mechanical", "android"],
    "harem": ["harem", "ハーレム", "multiple girls", "reverse harem", "polyamory"],
    "mature": ["mature", "成人", "adult", "18+", "explicit", "seinen"],
    "seinen": ["seinen", "青年", "adult male", "青年漫画", "青年向け"],
    "josei": ["josei", "女性", "adult female", "女性漫画", "女性向け"],
    "tragedy": ["tragic", "tragedy", "悲劇", "sad", "loss", "death"],
    "demons": ["demon", "demons", "悪魔", "devil", "fiend", "monster"],
    "magic": ["magic", "magical", "魔法", "sorcery", "wizard", "spell"],
    "martial arts": ["martial arts", "武道", "kung fu", "karate", "taekwondo", "judo", "fighting"],
    "vampire": ["vampire", "吸血鬼", "bloodsucker", "dracula", "undead"],
    "zombie": ["zombie", "ゾンビ", "undead", "walker", "infected"],
    "reincarnation": ["reincarnation", "転生", "rebirth", "re-born", "reincarnated"],
    "reverse harem": ["reverse harem", "リバースハーレム", "multiple boys", "polyandry"],
    "webtoon": ["webtoon", "ウェブトゥーン", "digital comic", "online comic", "manhwa"],
    "manhwa": ["manhwa", "マンファ", "korean comic", "webtoon", "k-comic"],
    "manga": ["manga", "マンガ", "japanese comic", "comic", "jp-comic"],
    "shoujo ai": ["shoujo ai", "少女愛", "girl's love", "yuri"],
    "shounen ai": ["shounen ai", "少年愛", "boy's love", "yaoi"],
    "doujinshi": ["doujinshi", "同人誌", "fan comic", "self-published"],
    "one shot": ["one shot", "ワンショット", "single chapter", "standalone"],
    "gender bender": ["gender bender", "ジェンダーベンダー", "gender swap", "sex change"],
    "parody": ["parody", "パロディ", "spoof", "satire", "gag"],
    "military": ["military", "軍事", "army", "war", "soldier"],
    "police": ["police", "警察", "cop", "detective", "law enforcement"],
    "samurai": ["samurai", "侍", "ronin", "bushi", "warrior"],
    "ninja": ["ninja", "忍者", "shinobi", "assassin"],
    "magic school": ["magic school", "魔法学校", "wizard school", "academy of magic"],
    "alien": ["alien", "宇宙人", "extraterrestrial", "space being"],
    "space": ["space", "宇宙", "outer space", "cosmos", "galaxy"],
    "cyberpunk": ["cyberpunk", "サイバーパンク", "future city", "high tech", "dystopia"],
    "steampunk": ["steampunk", "スチームパンク", "steam technology", "victorian tech"],
    "superpower": ["superpower", "超能力", "ability", "power", "hero"],
    "villain": ["villain", "悪役", "antagonist", "enemy", "bad guy"],
    "hero": ["hero", "ヒーロー", "protagonist", "champion", "savior"],
    "detective": ["detective", "探偵", "investigator", "sleuth", "gumshoe"],
    "crime": ["crime", "犯罪", "criminal", "lawbreaker", "felon"],
    "thriller": ["thriller", "スリラー", "suspense", "exciting", "tense"],
    "survival": ["survival", "サバイバル", "endurance", "escape", "outlast"],
    "apocalypse": ["apocalypse", "黙示録", "end of world", "post-apocalyptic", "doomsday"],
    "post-apocalyptic": ["post-apocalyptic", "終末", "after apocalypse", "ruins", "wasteland"],
    "magic girl": ["magic girl", "魔法少女", "mahou shoujo", "magical girl"],
    "idol": ["idol", "アイドル", "pop star", "celebrity", "singer"],
    "music": ["music", "音楽", "song", "band", "musician"],
    "cooking": ["cooking", "料理", "food", "chef", "cook"],
    "animal": ["animal", "動物", "pet", "creature", "beast"],
    "game": ["game", "ゲーム", "video game", "play", "competition"],
    "otome": ["otome", "乙女", "girl's game", "dating sim"],
    "shoujo fantasy": ["shoujo fantasy", "少女ファンタジー", "girl fantasy", "magical girl"],
    "shounen fantasy": ["shounen fantasy", "少年ファンタジー", "boy fantasy", "hero fantasy"],
    "office": ["office", "オフィス", "workplace", "company", "business"],
    "medical": ["medical", "医療", "doctor", "hospital", "nurse"],
    "family": ["family", "家族", "parent", "child", "siblings"],
    "friendship": ["friendship", "友情", "friend", "buddy", "companion"],
    "revenge": ["revenge", "復讐", "vengeance", "payback", "retribution"],
    "time travel": ["time travel", "タイムトラベル", "time machine", "past", "future"],
    "body swap": ["body swap", "ボディスワップ", "swap bodies", "identity switch"],
    "magic weapon": ["magic weapon", "魔法武器", "enchanted weapon", "legendary weapon"],
    "monster": ["monster", "モンスター", "creature", "beast", "fiend"],
    "ghost": ["ghost", "幽霊", "spirit", "phantom", "specter"],
    "spirit": ["spirit", "精霊", "ghost", "soul", "entity"],
    "curse": ["curse", "呪い", "hex", "jinx", "spell"],
    "teacher": ["teacher", "先生", "instructor", "professor", "mentor"],
    "student": ["student", "学生", "pupil", "learner", "scholar"],
    "child": ["child", "子供", "kid", "boy", "girl"],
    "adult": ["adult", "大人", "grown-up", "mature", "senior"],
    "elder": ["elder", "老人", "old man", "old woman", "senior"],
    "robot": ["robot", "ロボット", "android", "mecha", "machine"],
    "android": ["android", "アンドロイド", "robot", "cyborg", "mecha"],
    "cyborg": ["cyborg", "サイボーグ", "android", "robot", "machine"],
    "giant": ["giant", "巨人", "large", "huge", "colossal"],
    "tiny": ["tiny", "小さい", "small", "mini", "dwarf"],
    "rich": ["rich", "金持ち", "wealthy", "millionaire", "billionaire"],
    "poor": ["poor", "貧乏", "destitute", "pauper", "homeless"],
    "king": ["king", "王", "monarch", "ruler", "emperor"],
    "queen": ["queen", "女王", "monarch", "ruler", "empress"],
    "prince": ["prince", "王子", "royal", "heir", "noble"],
    "princess": ["princess", "王女", "royal", "heir", "noble"],
    "knight": ["knight", "騎士", "warrior", "paladin", "soldier"],
    "wizard": ["wizard", "魔法使い", "mage", "sorcerer", "magician"],
    "witch": ["witch", "魔女", "sorceress", "enchantress", "magician"],
    "fairy": ["fairy", "妖精", "sprite", "pixie", "elf"],
    "elf": ["elf", "エルフ", "fairy", "sprite", "pixie"],
    "demon king": ["demon king", "魔王", "devil king", "overlord", "evil lord"],
    "god": ["god", "神", "deity", "divinity", "creator"],
    "angel": ["angel", "天使", "cherub", "seraph", "messenger"],
    "beast": ["beast", "獣", "monster", "creature", "fiend"],
    "dragon": ["dragon", "ドラゴン", "wyvern", "drake", "serpent"],
    "cat": ["cat", "猫", "kitten", "feline", "kitty"],
    "dog": ["dog", "犬", "puppy", "canine", "hound"],
    "bird": ["bird", "鳥", "avian", "fowl", "chick"],
    "fish": ["fish", "魚", "seafood", "aquatic", "marine"],
    "sea": ["sea", "海", "ocean", "marine", "aquatic"],
    "mountain": ["mountain", "山", "peak", "summit", "hill"],
    "forest": ["forest", "森", "woods", "jungle", "grove"],
    "desert": ["desert", "砂漠", "wasteland", "dune", "arid"],
    "island": ["island", "島", "isle", "atoll", "archipelago"],
    "city": ["city", "都市", "town", "metropolis", "urban"],
    "village": ["village", "村", "hamlet", "settlement", "rural"],
    "country": ["country", "国", "nation", "state", "land"],
    "world": ["world", "世界", "earth", "planet", "globe"],
    "universe": ["universe", "宇宙", "cosmos", "galaxy", "space"],
}
